plugins {
    id "java"
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.8"
}

group = "me.Tonus_"
version = "3.0.0"

repositories {
    mavenCentral()
    maven { url = "https://repo.papermc.io/repository/maven-public/" }
    mavenLocal()
}

dependencies {
    implementation "org.bstats:bstats-bukkit:3.0.2"
    implementation "org.reflections:reflections:0.10.2"
    compileOnly "org.jetbrains:annotations:24.1.0"
    compileOnly "org.projectlombok:lombok:1.18.32"
    annotationProcessor "org.projectlombok:lombok:1.18.32"

    compileOnly "com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT"
    compileOnly "com.google.code.gson:gson:2.11.0" // CVE mitigation: spigot-api
    compileOnly "com.google.guava:guava:33.2.1-jre" // CVE mitigation: spigot-api
    compileOnly "org.yaml:snakeyaml:2.2" // CVE mitigation: spigot-api
    compileOnly 'junit:junit:4.13.2' // CVE mitigation: spigot-api
}

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

idea {
    module {
        excludeDirs = [
                file(".gradle"),
                file("build"),
                file("gradle"),
                file("gradlew"),
                file("gradlew.bat")
        ]
    }
}

sourceSets {
    main {
        java {
            srcDirs = ["src/main/java"]
        }

        resources {
            srcDirs = ["src/main/resources/"]
        }
    }
}

build.dependsOn shadowJar
shadowJar {
    relocate "org.bstats", "${project.group}.shaded.org.bstats"
    archiveFileName.set("${project.name}-${project.version}.jar")

    manifest {
        attributes("Implementation-Version": project.version)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.register("copyToTestServer", Copy) {
    dependsOn "build"
    mustRunAfter "build"

    from "${project.layout.buildDirectory}/libs"
    into "${project.layout.projectDirectory}/src/main/test/server/plugins"
    include "*.jar"
}

tasks.register("runOnTestServer", Exec) {
    dependsOn "copyToTestServer"
    mustRunAfter "copyToTestServer"

    workingDir "${project.layout.projectDirectory}/src/main/test/server/"
    commandLine "java", "-Xms1G", "-Xmx1G", "-Dpaper.log-level=WARN", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "paper-1.20.4-496.jar", "--nogui"
}
