main: me.Tonus_.hatCosmetics.Main
name: HatCosmetics
website: https://github.com/Supermarcel10/HatCosmetics/
version: ${pluginVersion}
api-version: 1.16
load: STARTUP
description: A simple plugin that allows players to wear hats.
authors:
  - Supermarcel10
  - Tonus_
