name: Build Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
  release:
    needs: build
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: plugin-jar
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.jar
