name: PR Checks

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  test:
    uses: ./.github/workflows/_test.yml
  build:
    uses: ./.github/workflows/_build.yml
